project_id = "csxrrefkjqflxcynbixj"

[functions.get-enrollments]
verify_jwt = false

[functions.get-leaderboard]
verify_jwt = false

[functions.update-profile]
verify_jwt = false

[functions.trigger-registration-webhook]
verify_jwt = false
