project_id = "csxrrefkjqflxcynbixj"

[functions.get-enrollments]
verify_jwt = false

[functions.get-leaderboard]
verify_jwt = false

[functions.update-profile]
verify_jwt = false

[functions.trigger-registration-webhook]
verify_jwt = false

[functions.get-public-sessions]
verify_jwt = false

[functions.check-registration-status]
verify_jwt = false

[functions.get-cohort-detail]
verify_jwt = false

[functions.get-unenrolled-users]
verify_jwt = false

[functions.update-registration-status]
verify_jwt = false

[functions.create-razorpay-order]
verify_jwt = false

[functions.verify-razorpay-payment]
verify_jwt = false
