/**
 * Bundles certificate HTML/CSS assets into TypeScript string modules
 * for Supabase Edge Functions (only .ts files are shipped to runtime).
 *
 * Usage: deno run --allow-read --allow-write scripts/bundle-certificate-assets.ts
 */

const ASSETS_DIR = new URL(
  "../supabase/functions/_shared/certificate-assets/",
  import.meta.url,
);

const ASSETS: Array<{ source: string; exportName: string }> = [
  { source: "foundation-certificate.html", exportName: "foundationCertificateHtml" },
  { source: "practitioner-certificate.html", exportName: "practitionerCertificateHtml" },
  { source: "expert-certificate.html", exportName: "expertCertificateHtml" },
  { source: "certificate-base.css", exportName: "certificateBaseCss" },
  { source: "certificate-dark-theme.css", exportName: "certificateDarkThemeCss" },
];

const HEADER =
  "// AUTO-GENERATED by scripts/bundle-certificate-assets.ts — do not edit\n";

for (const { source, exportName } of ASSETS) {
  const sourcePath = new URL(source, ASSETS_DIR);
  let contents: string;
  try {
    contents = await Deno.readTextFile(sourcePath);
  } catch {
    console.error(`Missing source file: ${sourcePath.pathname}`);
    Deno.exit(1);
  }

  if (!contents.trim()) {
    console.error(`Empty source file: ${source}`);
    Deno.exit(1);
  }

  const outName = `${source}.ts`;
  const outPath = new URL(outName, ASSETS_DIR);
  const outBody = `${HEADER}export const ${exportName} = ${JSON.stringify(contents)};\n`;
  await Deno.writeTextFile(outPath, outBody);
  console.log(`Wrote ${outName}`);
}

console.log("Done — bundled 5 certificate assets.");
